configMapGenerator:
- files:
  - application.yml
  name: 82187227-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepgstapacr.azurecr.io/82187227
  newTag: "202410091227"
- name: cepgstapacr.azurecr.io/cloud-sample
  newTag: "202410091123"
